//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicSite.Resources.ContactForm", typeof(ContactForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אני מאשר/ת את התנאים.
        /// </summary>
        public static string ConsentCheckbox {
            get {
                return ResourceManager.GetString("ConsentCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הצלחנו לשלוח את ההודעה. נסו שוב או פנו אלינו בטלפון..
        /// </summary>
        public static string ContactError {
            get {
                return ResourceManager.GetString("ContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההודעה נשלחה בהצלחה. נחזור אליכם בהקדם..
        /// </summary>
        public static string ContactSent {
            get {
                return ResourceManager.GetString("ContactSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אני מסכים/ה לקבל הודעות טקסט ממשרד עורכי הדין אלי קליימן. הודעות שיישלחו עשויות לכלול תגובה בעקבות בקשתי ליצירת קשר, עדכוני טיפול בעבודה משפטית, תורים ותזכורות, בקשות מידע, ומעקב בדוא&quot;ל. תדירות ההודעות תשתנה בהתאם לאינטראקציות עם הלקוחות, כאשר תזכורות ועדכונים יישלחו לפי הצורך. לחץ/י כאן כדי לצפות ב&lt;a href=&quot;{0}&quot;&gt;מדיניות הפרטיות&lt;/a&gt; ו&lt;a href=&quot;{1}&quot;&gt;בתנאי השימוש&lt;/a&gt; של האתר..
        /// </summary>
        public static string SmsConsentNotice {
            get {
                return ResourceManager.GetString("SmsConsentNotice", resourceCulture);
            }
        }
        
        public static string PlaceholderFullName {
            get {
                return ResourceManager.GetString("PlaceholderFullName", resourceCulture);
            }
        }
        
        public static string PlaceholderPhone {
            get {
                return ResourceManager.GetString("PlaceholderPhone", resourceCulture);
            }
        }
        
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        public static string PlaceholderMessage {
            get {
                return ResourceManager.GetString("PlaceholderMessage", resourceCulture);
            }
        }
    }
}
