<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
    <Folder Include="Models\" />
    <Folder Include="wwwroot\images\blog\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ContactForm.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ContactForm.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Resources\ContactForm.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContactForm.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataManager\DataManager.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Options\Options.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

</Project>
